{"uid":"5c78b5c0618a2c4e","name":"User is not allowed to enter invalid phone number","fullName":"tests.test_login.TestLogin#test_invalid_phone_number","historyId":"94f93c0710e43c69cf3d1609e68099c8","time":{"start":1684826886020,"stop":1684826888590,"duration":2570},"description":"User is not allowed to enter invalid phone number","descriptionHtml":"<p>User is not allowed to enter invalid phone number</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":2,"retriesStatusChange":true,"beforeStages":[{"name":"setup","time":{"start":1684826874788,"stop":1684826886016,"duration":11228},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"User is not allowed to enter invalid phone number","status":"passed","steps":[{"name":"User clicks login icon in nav bar","time":{"start":1684826886021,"stop":1684826887099,"duration":1078},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Fill phone number","time":{"start":1684826887099,"stop":1684826887761,"duration":662},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"phone_number","value":"'11111111111'"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"User clicks start exploring","time":{"start":1684826887761,"stop":1684826888363,"duration":602},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[{"uid":"f03d85328af336a1","name":"stdout","source":"f03d85328af336a1.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":3,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[{"name":"setup::0","time":{"start":1684826888591,"stop":1684826889072,"duration":481},"status":"passed","steps":[],"attachments":[{"uid":"655fd3e46b4cb8aa","name":"Screenshot","source":"655fd3e46b4cb8aa.png","type":"image/png","size":126050}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"labels":[{"name":"tag","value":"chrome"},{"name":"story","value":"Login functionality"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"e7a5f6497e16"},{"name":"thread","value":"20-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'chrome'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"328e14d7c78d1017","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb68ebe90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614050,"stop":1684826614050,"duration":0}},{"uid":"3caec635f169fe72","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7bd75cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531275,"stop":1684826531275,"duration":0}}],"categories":[],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"397921096c8d5b8b","reportUrl":"../4/index.html#testresult/397921096c8d5b8b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb68ebe90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614050,"stop":1684826614050,"duration":0}},{"uid":"bae256c4470baaa5","reportUrl":"../3/index.html#testresult/bae256c4470baaa5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7bd75cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531275,"stop":1684826531275,"duration":0}}]},"tags":["chrome","@pytest.mark.usefixtures('setup')"]},"source":"5c78b5c0618a2c4e.json","parameterValues":["'chrome'"]}