{"uid":"dd43dd4474ee667b","name":"User is not allowed to enter invalid phone number","fullName":"tests.test_login.TestLogin#test_invalid_phone_number","historyId":"a8241406a7d72ac646d6a48aaecfd220","time":{"start":1684826893502,"stop":1684826895984,"duration":2482},"description":"User is not allowed to enter invalid phone number","descriptionHtml":"<p>User is not allowed to enter invalid phone number</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":2,"retriesStatusChange":true,"beforeStages":[{"name":"setup","time":{"start":1684826874791,"stop":1684826893496,"duration":18705},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"description":"User is not allowed to enter invalid phone number","status":"passed","steps":[{"name":"User clicks login icon in nav bar","time":{"start":1684826893503,"stop":1684826894040,"duration":537},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"Fill phone number","time":{"start":1684826894040,"stop":1684826894653,"duration":613},"status":"passed","steps":[],"attachments":[],"parameters":[{"name":"phone_number","value":"'11111111111'"}],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"User clicks start exploring","time":{"start":1684826894653,"stop":1684826895921,"duration":1268},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[{"uid":"7cff245c4cf3b51f","name":"stdout","source":"7cff245c4cf3b51f.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":3,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[{"name":"setup::0","time":{"start":1684826895986,"stop":1684826898221,"duration":2235},"status":"passed","steps":[],"attachments":[{"uid":"1b02081a887597a1","name":"Screenshot","source":"1b02081a887597a1.png","type":"image/png","size":200954}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true}],"labels":[{"name":"tag","value":"firefox"},{"name":"story","value":"Login functionality"},{"name":"tag","value":"@pytest.mark.usefixtures('setup')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"subSuite","value":"TestLogin"},{"name":"host","value":"e7a5f6497e16"},{"name":"thread","value":"29-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"browser","value":"'firefox'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"436643fab748981d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff891a7a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614049,"stop":1684826614049,"duration":0}},{"uid":"de932e606e21db97","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffacfe5e10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531272,"stop":1684826531272,"duration":0}}],"categories":[],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"4536443c46cdac97","reportUrl":"../4/index.html#testresult/4536443c46cdac97","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff891a7a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826614049,"stop":1684826614049,"duration":0}},{"uid":"340d82bf29c6403f","reportUrl":"../3/index.html#testresult/340d82bf29c6403f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffacfe5e10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1684826531272,"stop":1684826531272,"duration":0}}]},"tags":["firefox","@pytest.mark.usefixtures('setup')"]},"source":"dd43dd4474ee667b.json","parameterValues":["'firefox'"]}