{"name": "User is able to login,this should fail", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16", "trace": "self = <tests.test_login.TestLogin object at 0xffff8e423c10>\n\n>   ???\n\n/Users/alya/Documents/selenium-ci-cd/tests/test_login.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/login_page.py:56: in login_existing_user\n    assert self.get_user_name() == \"Hi, \"+username\npages/nav_bar_page.py:25: in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\npages/base_page.py:33: in get_text\n    element: WebElement = self.wait.until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"598ab7b5-1f3d-481c-b2d2-49fae0d99fa7\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0xffff8e4aaa20>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\nE       element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n\n/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException"}, "description": "User is able to login", "steps": [{"name": "User logs in", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n\n", "trace": "  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/login_page.py\", line 56, in login_existing_user\n    assert self.get_user_name() == \"Hi, \"+username\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/nav_bar_page.py\", line 25, in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/base_page.py\", line 33, in get_text\n    element: WebElement = self.wait.until(\n                          ^^^^^^^^^^^^^^^^\n  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "User clicks login icon in nav bar", "status": "passed", "start": 1684827279397, "stop": 1684827279984}, {"name": "Fill phone number", "status": "passed", "parameters": [{"name": "phone_number", "value": "'01116888790'"}], "start": 1684827279984, "stop": 1684827281445}, {"name": "User clicks start exploring", "status": "passed", "start": 1684827281446, "stop": 1684827282090}, {"name": "User fill password", "status": "passed", "parameters": [{"name": "password", "value": "'test'"}], "start": 1684827282090, "stop": 1684827283995}, {"name": "User clicks login button", "status": "passed", "start": 1684827283996, "stop": 1684827284654}, {"name": "Return username when user logged in", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n\n", "trace": "  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/nav_bar_page.py\", line 25, in get_user_name\n    return self.get_text(self.LOGGED_IN_USER)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/selenium-test/pages/base_page.py\", line 33, in get_text\n    element: WebElement = self.wait.until(\n                          ^^^^^^^^^^^^^^^^\n  File \"/root/.local/share/virtualenvs/selenium-test-Ou9L0FGN/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1684827284655, "stop": 1684827316252}], "parameters": [{"name": "phone_number", "value": "'01116888790'"}, {"name": "password", "value": "'test'"}, {"name": "username", "value": "'alyaothman'"}], "start": 1684827279397, "stop": 1684827316263}], "attachments": [{"name": "stdout", "source": "bb34997c-2f60-4deb-8f9f-431061fdfe17-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser", "value": "'firefox'"}], "start": 1684827279396, "stop": 1684827316265, "uuid": "0993a6f8-4c73-4c47-ba90-f021c151fd60", "historyId": "88abe5aa9c6c37e78b845a216ec154ba", "testCaseId": "0edf0a627e33dcf0062a7d9e3e848ac1", "fullName": "tests.test_login.TestLogin#test_user_login", "labels": [{"name": "tag", "value": "firefox"}, {"name": "story", "value": "Login functionality"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "c84a2fb0e6ff"}, {"name": "thread", "value": "36-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}