{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x0000000100967598 chromedriver + 4973976\n1   chromedriver                        0x000000010095e913 chromedriver + 4938003\n2   chromedriver                        0x000000010051bcd6 chromedriver + 470230\n3   chromedriver                        0x000000010055f2ff chromedriver + 746239\n4   chromedriver                        0x000000010055f591 chromedriver + 746897\n5   chromedriver                        0x00000001005a1384 chromedriver + 1016708\n6   chromedriver                        0x00000001005839ed chromedriver + 895469\n7   chromedriver                        0x000000010059e856 chromedriver + 1005654\n8   chromedriver                        0x0000000100583793 chromedriver + 894867\n9   chromedriver                        0x000000010055121f chromedriver + 688671\n10  chromedriver                        0x000000010055256e chromedriver + 693614\n11  chromedriver                        0x0000000100921bb7 chromedriver + 4688823\n12  chromedriver                        0x0000000100926a51 chromedriver + 4708945\n13  chromedriver                        0x000000010092d40f chromedriver + 4736015\n14  chromedriver                        0x000000010092791a chromedriver + 4712730\n15  chromedriver                        0x00000001008fa87c chromedriver + 4528252\n16  chromedriver                        0x0000000100946f28 chromedriver + 4841256\n17  chromedriver                        0x00000001009470a7 chromedriver + 4841639\n18  chromedriver                        0x000000010095828f chromedriver + 4911759\n19  libsystem_pthread.dylib             0x00007fff204068fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff20402443 thread_start + 15","children":[{"name":"User is able to login,this should fail","uid":"d7b9bb25454da721","parentUid":"e58ed9e739dab7be30e9f373a264212b","status":"broken","time":{"start":1684825090955,"stop":1684825133127,"duration":42172},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":["'chrome'"],"tags":["chrome","@pytest.mark.usefixtures('setup')"]}],"uid":"e58ed9e739dab7be30e9f373a264212b"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff891a7a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is not allowed to enter invalid phone number","uid":"4536443c46cdac97","parentUid":"35bf4c40d27f3656fa159282c16ef569","status":"broken","time":{"start":1684826614049,"stop":1684826614049,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":["'firefox'"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"35bf4c40d27f3656fa159282c16ef569"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffa89abcd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is not allowed to enter alpha characters","uid":"f040e2f2341c5e8d","parentUid":"b3d73440c5acaa2ac4f302f30eb9f3b9","status":"broken","time":{"start":1684826614050,"stop":1684826614050,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":["'chrome'"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"b3d73440c5acaa2ac4f302f30eb9f3b9"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb68ebe90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is not allowed to enter invalid phone number","uid":"397921096c8d5b8b","parentUid":"bc8a2692551f6bb310415de81e4783bd","status":"broken","time":{"start":1684826614050,"stop":1684826614050,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":["'chrome'"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"bc8a2692551f6bb310415de81e4783bd"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff89b9bd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is not allowed to enter alpha characters","uid":"3466d084f7378e2c","parentUid":"eff6a195d78bcdd44a486d3ad39bfa13","status":"broken","time":{"start":1684826614051,"stop":1684826614051,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":["'firefox'"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"eff6a195d78bcdd44a486d3ad39bfa13"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff998e4150>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is able to login,this should fail","uid":"3340757861709241","parentUid":"da50976be8e93b13b5d9758f8f75aa3d","status":"broken","time":{"start":1684826614052,"stop":1684826614052,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":["'chrome'"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"da50976be8e93b13b5d9758f8f75aa3d"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffaa577b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is able to change country code","uid":"edefa6f04fb11bfc","parentUid":"d4c1c459a9efde4e56937e86f59c9bd9","status":"broken","time":{"start":1684826614082,"stop":1684826614082,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":["'firefox'","{'country': 'Afghanistan', 'code': '+93'}"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"d4c1c459a9efde4e56937e86f59c9bd9"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7d9ef9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is able to login,this should fail","uid":"a6e27f000ae1f5e1","parentUid":"48ebc34d3ab1fd3487e0484aa8b3a233","status":"broken","time":{"start":1684826614083,"stop":1684826614083,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":["'firefox'"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"48ebc34d3ab1fd3487e0484aa8b3a233"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7ccdbc90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is able to change country code","uid":"9d52666f86115bed","parentUid":"d215701cf4ae6fac41d81af0f2dce732","status":"broken","time":{"start":1684826614087,"stop":1684826614087,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":["'chrome'","{'country': 'Afghanistan', 'code': '+93'}"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"d215701cf4ae6fac41d81af0f2dce732"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff88b47210>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is able to change country code","uid":"ddba4939fe5e4a1d","parentUid":"c34234ce467912bc04fc6614165537f4","status":"broken","time":{"start":1684826614445,"stop":1684826614445,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":1,"retriesStatusChange":true,"parameters":["'firefox'","{'country': 'Albania', 'code': '+355'}"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"c34234ce467912bc04fc6614165537f4"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='selenium-hub', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffffb628b590>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"User is able to change country code","uid":"47cc474944e860c5","parentUid":"7e2259e5f6413378063ae57c046b6003","status":"broken","time":{"start":1684826614677,"stop":1684826614677,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":1,"retriesStatusChange":true,"parameters":["'chrome'","{'country': 'Albania', 'code': '+355'}"],"tags":["@pytest.mark.usefixtures('setup')"]}],"uid":"7e2259e5f6413378063ae57c046b6003"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}